"""Write index.html for a *static* host (Render Static Site, GitHub Pages, ...).

    python ports/soh/make_static_front.py [out=index.html] [upstream-url]

The page fetches the published site's index.html, adds a <base> pointing at it (so soh.js, soh.wasm and
the .o2r archives load from the original site), injects ports/soh/chromebook.js, and runs it.
history.replaceState is wrapped because the site's boot script passes absolute paths, which would
otherwise resolve against the <base> origin and throw. If anything fails the visitor is sent to the
original site. ?upstream=<url> overrides the source (for testing).
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
UPSTREAM = "https://andrewnakas.github.io/oot-cleanroom"

PAGE = r"""<!doctype html>
<html lang="ko"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<title>Ocarina of Time Clean Room</title>
<!-- GENERATED by ports/soh/make_static_front.py: do not edit. -->
<style>html,body{margin:0;background:#000;color:#9aa;font:16px sans-serif;height:100%}#cr-boot{position:fixed;inset:0;display:flex;align-items:center;justify-content:center;text-align:center}</style>
</head><body><div id="cr-boot">시간의 오카리나를 불러오는 중입니다...<br>처음에는 1~2분 걸릴 수 있어요. 잠시만 기다려 주세요.</div>
<script>
(function(){
  var UP = (new URLSearchParams(location.search).get('upstream') || @UPSTREAM@).replace(/\/+$/, '') + '/';
  var CB = @CB@;
  var FIX = "(function(){var h=location.href;['replaceState','pushState'].forEach(function(n){var o=history[n];" +
            "history[n]=function(s,t,u){return o.call(history,s,t,u==null?u:new URL(u,h).href);};});})();";
  fetch(UP + 'index.html', {cache: 'no-cache'}).then(function(r){
    if(!r.ok) throw new Error(r.status); return r.text();
  }).then(function(s){
    if(s.indexOf('</head>') < 0) throw new Error('no head');
    var close = '<' + '/script>';
    s = s.replace('<head>', '<head><script>' + FIX + close + '<base href="' + UP + '">');
    s = s.replace('</head>', '<script>' + CB.split(close).join('<\\/script>') + close + '</head>');
    document.open(); document.write(s); document.close();
  }).catch(function(e){ console.error('front:', e); location.replace(UP + location.hash); });
})();
</script></body></html>
"""


def main(argv):
    out = argv[1] if len(argv) > 1 else "index.html"
    up = argv[2] if len(argv) > 2 else UPSTREAM
    cb = open(os.path.join(HERE, "chromebook.js"), encoding="utf-8").read()
    html = PAGE.replace("@UPSTREAM@", json.dumps(up)).replace("@CB@", json.dumps(cb).replace("</", "<\\/"))
    open(out, "w", encoding="utf-8", newline="\n").write(html)
    print("wrote", out, len(html), "bytes")


if __name__ == "__main__":
    main(sys.argv)
